    
server: 
  port: 18101

weather:
  weatherCityIdUrl: http://wthrcdn.etouch.cn/weather_mini?citykey={citykey}
  weatherCityNameUrl: http://wthrcdn.etouch.cn/weather_mini?city={city}
  cityId: 101190101
  ipDataPath: /apps/weather/ipdata.datx
  
spring:
  aop:
    auto: true
    proxy-target-class: true
  freemarker:
    charset: UTF-8
    check-template-location: true
    enabled: true
    prefix:
    suffix:
    request-context-attribute: request
    template-loader-path: classpath:/templates/
    view-names: '*.ftl'